version: '3'
services:
  backend:
    container_name: ncinga-timmer-api-container
    image: ncinga-timmer-api:v1
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    container_name: ncinga-timmer-web-container
    image: ncinga-timmer-web:v1
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    dns:
      - 8.8.8.8
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
